//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.25 at 04:59:31 PM IST 
//


package customerOrderXSDClasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the customerOrderXSDClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: customerOrderXSDClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomerOrder }
     * 
     */
    public CustomerOrder createCustomerOrder() {
        return new CustomerOrder();
    }

    /**
     * Create an instance of {@link CustomerOrder.Customer }
     * 
     */
    public CustomerOrder.Customer createCustomerOrderCustomer() {
        return new CustomerOrder.Customer();
    }

    /**
     * Create an instance of {@link CustomerOrder.Customer.Address }
     * 
     */
    public CustomerOrder.Customer.Address createCustomerOrderCustomerAddress() {
        return new CustomerOrder.Customer.Address();
    }

}
